name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/cicd'
#      - 'main'
#      - 'dev'
#  pull_request:
#    branches:
#      - 'main'
#      - 'dev'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push Docker image to GCP Artifact Registry
        run: |
          docker build -t ${{ secrets.GCP_ARTIFACT_REGISTRY }}:${{ github.sha }} .
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY }}:${{ github.sha }}

      - name: Deploy to GCE instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          script: |
            docker login asia-northeast3-docker.pkg.dev -u _json_key -p "${{ secrets.GCP_SA_KEY }}"
            docker pull ${{ secrets.GCP_ARTIFACT_REGISTRY }}:${{ github.sha }}
            docker stop $(docker ps -aq) || true
            docker run -d --rm ${{ secrets.GCP_ARTIFACT_REGISTRY }}:${{ github.sha }}
