name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/cicd'
#      - 'main'
#      - 'dev'
#  pull_request:
#    branches:
#      - 'main'
#      - 'dev'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - name: Set up JDK 17
        uses: 'actions/setup-java@v3'
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Setup GCP Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push Docker image to GCP Artifact Registry
        run: |
          docker build -t ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }} .
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }}

      - name: Deploy to GCE instance
        run: |
          gcloud compute instances update-container "tfinder-vm" \
            --zone "asia-northeast3-a" \
            --container-image "${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }}"

#      - name: Connect to GCE instance and run commands
#        run: |
#          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
#          gcloud compute scp gcp-key.json tfinder-vm:~/ --zone asia-northeast3-a
#          gcloud compute ssh tfinder-vm --zone asia-northeast3-a --command="\
#            gcloud auth activate-service-account --key-file=gcp-key.json && \
#            gcloud config set account && \
#            gcloud components update && \
#            gcloud auth configure-docker asia-northeast3-docker.pkg.dev -q && \
#            gcloud projects get-iam-policy ${{ secrets.GCP_PROJECT_ID }} && \
#            sudo docker pull ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }} && \
#            sudo docker stop tfinder-container || true && \
#            sudo docker rm tfinder-container || true && \
#            sudo docker run -d --name tfinder-container -p 8080:8080 ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }}"
#          rm gcp-key.json

#      - name: Deploy to GCE instance
#        uses: appleboy/ssh-action@v0.1.6
#        with:
#          host: ${{ secrets.GCE_HOST }}
#          username: ${{ secrets.GCE_USERNAME }}
#          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
#          script: |
#            echo "${{ secrets.GCP_SA_KEY_LINE }}" | docker login asia-northeast3-docker.pkg.dev -u _json_key --password-stdin && \
#            sudo docker pull ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }} && \
#            sudo docker stop tfinder-container || true && \
#            sudo docker rm tfinder-container || true && \
#            sudo docker run -d --name tfinder-container -p 8080:8080 ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }}
