name: CI/CD

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'feature/cicd'
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.ACTION_KEY }}

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: 'actions/setup-java@v3'
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Copy secret files from submodule
        run: ./gradlew copySecret copySecret2

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Setup GCP Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push Docker image to GCP Artifact Registry with cache
        run: |
          docker buildx create --use
          docker buildx build --push --tag ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }} \
            --cache-from=type=registry,ref=${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:cache \
            --cache-to=type=inline \
            .

      - name: Deploy to GCE instance
        run: |
          gcloud compute instances update-container "tfinder-vm" \
            --zone "asia-northeast3-a" \
            --container-image "${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }}"