name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/cicd'
#      - 'main'
#      - 'dev'
#  pull_request:
#    branches:
#      - 'main'
#      - 'dev'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - name: Set up JDK 17
        uses: 'actions/setup-java@v3'
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Setup GCP Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push Docker image to GCP Artifact Registry
        run: |
          docker build -t ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }} .
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }}

      - name: Deploy to GCE instance
        run: |
          gcloud compute instances update-container "tfinder-vm" \
            --zone "asia-northeast3-a" \
            --container-image "${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }}"

