name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/cicd'
#      - 'main'
#      - 'dev'
#  pull_request:
#    branches:
#      - 'main'
#      - 'dev'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup GCP Auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push Docker image to GCP Artifact Registry
        run: |
          docker build -t ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }} .
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }}

      - name: Deploy to GCE
        run: |
          gcloud compute ssh ${{ secrets.GCP_PROJECT_ID }} --zone asia-northeast3-a --command "\
            docker pull ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }} && \
            docker stop tfinder-container || true && \
            docker rm tfinder-container || true && \
            docker run -d -p 80:80 --name tfinder-container ${{ secrets.GCP_ARTIFACT_REGISTRY }}/tfinder:${{ github.sha }}"
